# Generated by Django 5.1.7 on 2025-05-24 15:26

import django.db.models.deletion
import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestSequenceTable4DjangoVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('self_reference', models.ForeignKey(db_default=django.db.models.expressions.RawSQL("currval('testapp_testsequencetable4djangoversion_id_seq')", ()), on_delete=django.db.models.deletion.CASCADE, to='testapp.testsequencetable4djangoversion')),
            ],
        ),
    ]
